# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TrendsAI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrendsAI
  	pod 'Firebase/Core'
	
	pod 'FirebaseUI/Auth'
	pod 'FirebaseUI/Twitter'

	pod 'TwitterKit', '~> 3.0'

	pod 'RxSwift',    '~> 4.0'
	pod 'RxCocoa',    '~> 4.0'
	pod 'SnapKit', '~> 4.0.0'
    pod 'SideMenu'
end
